# =====================================================================
# 🐳 DOCKER COMPOSE ДЛЯ TENDER AUTOMATION MVP
# =====================================================================
#
# Этот файл настраивает полное окружение для разработки и тестирования
# Включает все необходимые сервисы:
# - PostgreSQL (основная база данных)
# - Ollama (AI сервис для Llama модели)
# - Redis (кеширование, очереди) - для будущего расширения
# - Application (само приложение)
#
# TODO: При расширении функциональности добавить:
# - Elasticsearch (полнотекстовый поиск)
# - Grafana + Prometheus (мониторинг)
# - MinIO (файловое хранилище)
# - NGINX (reverse proxy)

version: '3.8'

services:
  # =====================================================================
  # 🗃️ POSTGRESQL - Основная база данных
  # =====================================================================
  postgres:
    image: postgres:15-alpine
    container_name: tender_postgres
    restart: unless-stopped
    
    # 🔐 Настройки аутентификации
    environment:
      POSTGRES_DB: tender_automation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_123}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    
    # 📊 Настройки производительности
    command: |
      postgres
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
    
    # 🗂️ Тома данных
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/migrations:ro
    
    # 🌐 Сетевые настройки
    ports:
      - "${DB_PORT:-5432}:5432"
    
    # 🔍 Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tender_automation"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
    # 🏷️ Метки для организации
    labels:
      - "tender-automation.service=database"
      - "tender-automation.environment=development"

  # =====================================================================
  # 🤖 OLLAMA - AI сервис для Llama модели
  # =====================================================================
  ollama:
    image: ollama/ollama:latest
    container_name: tender_ollama
    restart: unless-stopped
    
    # 🗂️ Тома для моделей
    volumes:
      - ollama_data:/root/.ollama
    
    # 🌐 Сетевые настройки
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    
    # 🔍 Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # 🏷️ Метки
    labels:
      - "tender-automation.service=ai"
      - "tender-automation.environment=development"
    
    # 📊 Ресурсы (опционально для ограничения)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 4G
    #     reservations:
    #       cpus: '1.0'
    #       memory: 2G

  # =====================================================================
  # 🔴 REDIS - Кеширование и очереди (для будущего расширения)
  # =====================================================================
  redis:
    image: redis:7-alpine
    container_name: tender_redis
    restart: unless-stopped
    
    # ⚙️ Конфигурация Redis
    command: |
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 60 1
    
    # 🗂️ Том для данных
    volumes:
      - redis_data:/data
    
    # 🌐 Сетевые настройки
    ports:
      - "${REDIS_PORT:-6379}:6379"
    
    # 🔍 Health check
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    
    # 🏷️ Метки
    labels:
      - "tender-automation.service=cache"
      - "tender-automation.environment=development"

  # =====================================================================
  # 🚀 APPLICATION - Основное приложение
  # =====================================================================
  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
      target: development  # Используем development стадию
    
    container_name: tender_app
    restart: unless-stopped
    
    # 🔗 Зависимости
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
      redis:
        condition: service_healthy
    
    # 🌐 Переменные окружения
    environment:
      # 🗃️ Database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-secure_password_123}
      DB_NAME: tender_automation
      DB_SSLMODE: disable
      
      # 🤖 AI
      AI_URL: http://ollama:11434
      AI_MODEL: ${AI_MODEL:-llama2}
      AI_TIMEOUT: 60s
      
      # 🔴 Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # 🖥️ Server
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      SERVER_MODE: debug
      
      # 📝 Logging
      LOG_LEVEL: debug
      LOG_FORMAT: console
      LOG_OUTPUT: stdout
      
      # 🎯 Business
      MIN_AI_SCORE_THRESHOLD: 0.7
      DEFAULT_PAGE_SIZE: 20
      MAX_PAGE_SIZE: 100
    
    # 🗂️ Тома для разработки
    volumes:
      - ..:/app:ro  # Read-only монтирование исходного кода
      - app_cache:/app/.cache  # Кеш для Go модулей
    
    # 🌐 Сетевые настройки
    ports:
      - "${SERVER_PORT:-8080}:8080"
    
    # 🔍 Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # 🏷️ Метки
    labels:
      - "tender-automation.service=api"
      - "tender-automation.environment=development"
    
    # 🔧 Команда запуска для development
    command: |
      sh -c "
        echo '🚀 Starting Tender Automation MVP...'
        echo '⏳ Waiting for dependencies...'
        sleep 10
        echo '🔧 Running migrations...'
        # TODO: Добавить команду миграций
        echo '🌐 Starting API server...'
        go run cmd/api/main.go
      "
    
    # 📊 Рабочая директория
    working_dir: /app

# =====================================================================
# 🗂️ ИМЕНОВАННЫЕ ТОМА
# =====================================================================
volumes:
  # PostgreSQL данные
  postgres_data:
    driver: local
    labels:
      - "tender-automation.volume=database"

  # Ollama модели и данные
  ollama_data:
    driver: local
    labels:
      - "tender-automation.volume=ai-models"

  # Redis данные
  redis_data:
    driver: local
    labels:
      - "tender-automation.volume=cache"

  # Кеш приложения
  app_cache:
    driver: local
    labels:
      - "tender-automation.volume=app-cache"

# =====================================================================
# 🌐 СЕТИ
# =====================================================================
networks:
  default:
    name: tender_automation_network
    labels:
      - "tender-automation.network=main"

# =====================================================================
# 🔧 ИНСТРУКЦИИ ПО ИСПОЛЬЗОВАНИЮ
# =====================================================================

# TODO: Команды для работы с Docker Compose:
#
# 🚀 Запуск всех сервисов:
#   docker-compose up -d
#
# 📋 Просмотр логов:
#   docker-compose logs -f app
#   docker-compose logs -f postgres
#   docker-compose logs -f ollama
#
# 🔍 Проверка статуса:
#   docker-compose ps
#   docker-compose top
#
# 🛑 Остановка сервисов:
#   docker-compose down
#
# 🗑️ Полная очистка (включая тома):
#   docker-compose down -v --remove-orphans
#
# 🔄 Перезапуск конкретного сервиса:
#   docker-compose restart app
#
# 📊 Подключение к базе данных:
#   docker-compose exec postgres psql -U postgres -d tender_automation
#
# 🤖 Загрузка AI модели:
#   docker-compose exec ollama ollama pull llama2
#   docker-compose exec ollama ollama list
#
# 🐳 Просмотр использования ресурсов:
#   docker stats $(docker-compose ps -q)
#
# 🔧 Выполнение команд в контейнере приложения:
#   docker-compose exec app go mod tidy
#   docker-compose exec app go test ./...
#
# 📝 Миграции базы данных:
#   docker-compose exec app migrate -path migrations -database "postgres://postgres:password@postgres:5432/tender_automation?sslmode=disable" up
#
# =====================================================================
# 🌍 ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
# =====================================================================

# TODO: Создайте .env файл в корне проекта:
#
# # Database
# DB_PASSWORD=your_secure_password
# DB_PORT=5432
#
# # AI
# AI_MODEL=llama2
# OLLAMA_PORT=11434
#
# # Application
# SERVER_PORT=8080
# LOG_LEVEL=debug
#
# # Redis
# REDIS_PORT=6379

# =====================================================================
# 🔒 БЕЗОПАСНОСТЬ ДЛЯ PRODUCTION
# =====================================================================

# TODO: Для production окружения:
#
# 1. 🔐 Используйте секреты вместо переменных окружения:
#    secrets:
#      db_password:
#        file: ./secrets/db_password.txt
#
# 2. 🌐 Настройте reverse proxy (nginx):
#    - Терминация SSL
#    - Сжатие контента
#    - Rate limiting
#    - Логирование доступа
#
# 3. 🛡️ Ограничьте доступ к сервисам:
#    - Уберите публикацию портов БД и Redis
#    - Используйте internal networks
#    - Настройте firewall правила
#
# 4. 📊 Добавьте мониторинг:
#    - Prometheus + Grafana
#    - Логирование в ELK stack
#    - Health checks и alerting
#
# 5. 🔄 Настройте backup:
#    - Автоматический backup PostgreSQL
#    - Репликация критичных данных
#    - Disaster recovery план

# =====================================================================
# ✅ ЗАКЛЮЧЕНИЕ
# =====================================================================

# Этот Docker Compose файл предоставляет:
# ✅ Полное окружение для разработки
# ✅ Все необходимые сервисы настроены
# ✅ Health checks для надежности
# ✅ Тома для персистентности данных
# ✅ Переменные окружения для настройки
# ✅ Метки для организации
#
# Для начала работы:
# 1. Скопируйте .env.example в .env
# 2. Запустите: docker-compose up -d
# 3. Проверьте: curl http://localhost:8080/health
# 4. Загрузите AI модель: docker-compose exec ollama ollama pull llama2