# 🕷️ Pipeline: Tender Discovery
# Конфигурация пайплайна для автоматического поиска тендеров

name: "tender-discovery"
version: "1.0"
description: "Автоматический поиск релевантных тендеров на закупочных площадках"

# ⏰ Расписание запуска
schedule:
  interval: "1h"           # Каждый час
  timezone: "Europe/Moscow"
  enabled: true

# 🔧 Конфигурация
config:
  # Платформы для парсинга
  platforms:
    - name: "zakupki.gov.ru"
      url: "https://zakupki.gov.ru/epz/order/extendedsearch/results.html"
      enabled: true
      priority: 1
      rate_limit: "5s"     # Задержка между запросами
      
    - name: "szvo.gov35.ru"  
      url: "https://szvo.gov35.ru/purchases"
      enabled: true
      priority: 2
      rate_limit: "3s"
      
    - name: "gz-spb.ru"
      url: "https://gz-spb.ru/search"
      enabled: true
      priority: 3
      rate_limit: "7s"

  # 🔍 Критерии поиска
  search_criteria:
    keywords:
      required:           # Обязательные ключевые слова
        - "медицинское оборудование"
        - "диагностическое оборудование"
        - "лабораторное оборудование"
        - "медицинские изделия"
        - "рентген"
        - "УЗИ"
        - "томограф"
        - "анализатор"
      
      optional:           # Дополнительные ключевые слова (бонус к релевантности)
        - "больница"
        - "поликлиника"
        - "медицинский центр"
        - "лечебное учреждение"
      
      excluded:           # Исключаемые слова
        - "услуги"
        - "ремонт"
        - "техническое обслуживание"
        - "строительство"
        - "программное обеспечение"
    
    # 💰 Ценовые фильтры
    budget:
      min_amount: 100000      # Минимум 100 тыс. руб.
      max_amount: 50000000    # Максимум 50 млн. руб.
      currency: "RUB"
    
    # 📅 Временные фильтры
    dates:
      start_date: "today"                    # Начиная с сегодня
      end_date: "+30d"                       # До 30 дней вперед
      min_deadline_days: 7                   # Минимум 7 дней до подачи заявок
    
    # 🏢 Фильтры заказчиков
    customer_types:
      - "медицинские учреждения"
      - "государственные больницы" 
      - "областные больницы"
      - "городские больницы"
      - "федеральные медицинские центры"

# 🔄 Этапы пайплайна
stages:
  # ЭТАП 1: Поиск и сбор тендеров
  - name: "scraping"
    type: "parallel"
    timeout: "30m"
    retry_count: 3
    
    steps:
      - name: "scrape_zakupki"
        type: "scraper"
        config:
          platform: "zakupki.gov.ru"
          max_pages: 10
          concurrent_requests: 3
          user_agent: "TenderBot/1.0 (Medical Equipment Scanner)"
          
      - name: "scrape_szvo"
        type: "scraper" 
        config:
          platform: "szvo.gov35.ru"
          max_pages: 5
          concurrent_requests: 2
          
      - name: "scrape_spb"
        type: "scraper"
        config:
          platform: "gz-spb.ru"
          max_pages: 3
          concurrent_requests: 2

  # ЭТАП 2: Предварительная фильтрация
  - name: "initial_filtering"
    type: "sequential"
    timeout: "10m"
    
    steps:
      - name: "deduplication"
        type: "filter"
        description: "Удаление дубликатов по номеру тендера"
        
      - name: "basic_validation"
        type: "validator"
        description: "Проверка обязательных полей"
        
      - name: "keyword_filtering"
        type: "filter"
        description: "Фильтрация по ключевым словам"

  # ЭТАП 3: AI анализ релевантности
  - name: "ai_analysis"
    type: "parallel"
    timeout: "45m"
    batch_size: 5        # Обрабатываем по 5 тендеров одновременно
    
    steps:
      - name: "relevance_analysis"
        type: "ai_processor"
        model: "llama4-maviric"
        config:
          prompt_template: "tender_relevance_analysis"
          confidence_threshold: 0.7
          max_tokens: 1000
          
      - name: "category_classification"
        type: "ai_processor"
        model: "llama4-maviric"
        config:
          prompt_template: "equipment_categorization"
          categories:
            - "диагностическое оборудование"
            - "лабораторное оборудование"
            - "хирургическое оборудование"
            - "терапевтическое оборудование"
            - "медицинские расходники"

  # ЭТАП 4: Сохранение результатов
  - name: "persistence"
    type: "sequential"
    timeout: "5m"
    
    steps:
      - name: "save_to_database"
        type: "database"
        description: "Сохранение тендеров в PostgreSQL"
        
      - name: "update_search_index"
        type: "search_index"
        description: "Обновление поискового индекса"
        
      - name: "emit_events"
        type: "event_emitter"
        description: "Отправка событий о новых тендерах"

# 📊 Мониторинг и алерты
monitoring:
  metrics:
    - name: "tenders_discovered"
      type: "counter"
      description: "Количество найденных тендеров"
      
    - name: "processing_time"
      type: "histogram"
      description: "Время обработки пайплайна"
      
    - name: "ai_analysis_accuracy"
      type: "gauge"
      description: "Точность AI анализа"
      
    - name: "error_rate"
      type: "counter"
      description: "Количество ошибок"

  alerts:
    - name: "no_tenders_found"
      condition: "tenders_discovered == 0"
      severity: "warning"
      notification: "slack"
      
    - name: "high_error_rate"
      condition: "error_rate > 10%"
      severity: "critical"
      notification: "email,slack"
      
    - name: "pipeline_timeout"
      condition: "processing_time > 60m"
      severity: "warning"
      notification: "slack"

# 🔧 Настройки восстановления
recovery:
  auto_retry: true
  max_retries: 3
  retry_delay: "5m"
  
  # Действия при критических ошибках
  on_failure:
    - action: "notify_admin"
      channels: ["email", "slack"]
    - action: "save_logs"
      retention: "7d"
    - action: "pause_pipeline"
      duration: "1h"

# 📈 Ожидаемые результаты
expected_results:
  tenders_per_run: 50-200      # Ожидаемое количество тендеров за запуск
  relevant_percentage: 15-30   # Процент релевантных тендеров
  processing_time: 30-60       # Время обработки в минутах
  ai_accuracy: 85-95           # Точность AI анализа в процентах

# 🧪 Тестирование
testing:
  enabled: true
  test_data: "test_tenders.json"
  
  acceptance_criteria:
    min_tenders_found: 10
    max_processing_time: "90m"
    min_ai_accuracy: 80
    max_error_rate: 5